settings:
  target_appids:
     - 20
     - 868020

steam_app_list:
  api_url: https://api.steampowered.com/ISteamApps/GetAppList/v2/
  columns:
    - appid
    - name

steam_news:
  api_url: https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/
  columns:
    - gid
    - title
    - url
    - is_external_url
    - author
    - contents
    - feedlabel
    - date
    - feedname
    - feed_type
    - appid
    - tags
  params:
    maxlength: 
    enddate:
    count: 2000
    feeds:

steam_appreviews:
  api_url: http://store.steampowered.com/appreviews/
  columns:
    - recommendationid
    - author_steamid
    - author_num_games_owned
    - author_num_reviews
    - author_playtime_forever
    - author_playtime_last_two_weeks
    - author_playtime_at_review
    - author_last_played
    - language
    - review
    - timestamp_created
    - timestamp_updated
    - voted_up
    - votes_up
    - votes_funny
    - weighted_vote_score
    - steam_purchase
    - received_for_free
    - hidden_in_steam_china
    - written_during_early_access
    - developer_response
    - timestamp_dev_responded
  params:
    json: 1
    filter: recent
    language: all
    review_type: all
    purchase_type: all
    num_per_page: 100
    filter_offtopic_activity: 0