settings:
  target_appids:
    - 730
    - 440
    - 400
    - 10

steam_app_list:
  api_url: https://api.steampowered.com/ISteamApps/GetAppList/v2/
  columns:
    - appid
    - name

steam_news:
  api_url: https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/
  columns:
    - gid
    - title
    - url
    - is_external_url
    - author
    - contents
    - feedlabel
    - date
    - feedname
    - feed_type
    - appid
    - tags
  params:
    maxlength: 
    enddate:
    count: 2000
    feeds: